# Generated by Django 3.0.3 on 2020-12-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_course_courseattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattendance',
            name='mark',
            field=models.BooleanField(default=False),
        ),
    ]
